182 model pick view
Reactor-Army/reactor_frontend pull request #194
Opened 2021-09-23 00:16 UTC by Santiago-Pinto

closes #182 and #185

2021-09-23 01:03 UTC, lucaslavandeira commented on src/components/ExpandableSidebarItem/ExpandableSidebarItem.jsx
> +          return (
Creo que este return es innecesario si metes el => ( en vez de => {

2021-09-23 01:03 UTC, lucaslavandeira commented on src/components/Sidebar/SidebarContent.jsx
> +      <ExpandableSidebarItem title={models.title} items={models.items} />
no me gusta que hayas hardcodeado la presencia de ests items en la sidebar aparte de los demás. Lo optimo sería que fueran parte del objeto routes. Quizás agregando un flag mas en el objeto, o algo para diferenciarlo de los comunes. Otra opción sería que las otras categorías también fueran expandibles...

2021-09-23 02:04 UTC, MatiasReimondo requested changes
En responsive cuando seleccionas cualquiera de las opciones dle menu de curvas, no te escode la barra, si te cambia la pantalla pero no te das cuenta por que no te cierra la barra.
Lo demas lo vi bien y muy cheto

2021-09-23 12:52 UTC, lucaslavandeira commented
+1 a lo que dice Mati, es verdad que en mobile si haces click en uno de los 3 modelos en la sidebar, no se cierra, lo que sí sucede con las demás opciones

Otra observación es que se me hacen medio vacías las cards en mobile, no estaría bueno agregarle la imagen tambien? Comprendo que es un desafío adicional diseñar eso

2021-09-23 22:38 UTC, MatiasReimondo approved these changes
Ahora sí, una genialidad

2021-09-24 00:09 UTC, lucaslavandeira commented
Me preocupa que sigue sin ser lo suficientemente flexible la sidebar. Si yo quisiera tener un elemento "composed" arriba, o entre los elementos simples, no se puede. Igual sabés qué, te acepto crear un issue de refactor y nunca tomarlo

2021-09-24 22:17 UTC, lucaslavandeira approved these changes

2021-09-24 22:20 UTC, merged